### PR TITLE
An API that constructs the bounds matrix and the L_BFGS_B struct

### PR DESCRIPTION
**Pull request by raminammour**
Hello,

Thanks for wrapping the lbfgsb library!

I think this interface is a bit more high level, `lbfgsb` can be exported and documented. Normally users solve with one problem size, and I could never remember what the bounds mean :)

Let me know if you think this is useful, and I can document/test and export these functions.

Cheers!

### CODE REVIEW

**Comment by Gnimuc** [comment]
Thanks for your contribution! This looks good. I'll merge it when the documentation and tests are added. 😉

**Comment by raminammour** [comment]
Do you want `lbfgsb` documented as the main API or as an additional (secondary) API to the existing one?

**Comment by Gnimuc** [comment]
I guess it's more like a helper function over the original one. We can mention it in the README and add some docstrings with a simple example.

**Comment by raminammour** [comment]
I added some tests and some help in the README. `LBFGS_B` does not have doc strings itself to piggy back off of those so I relied on the README. Let me know if this is sufficient.

**Comment by Gnimuc** [comment]
LGTM. Thanks again!

**Pull request merged**
